"""
Configuration settings for Project Cortana.
"""

import os
from pathlib import Path

# Project root directory
PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Important directories
DATA_DIR = PROJECT_ROOT / "data"
LOG_DIR = PROJECT_ROOT / "logs"
DOCS_DIR = PROJECT_ROOT / "docs"
TESTS_DIR = PROJECT_ROOT / "tests"

# Application information
APP_NAME = "Project Cortana"
APP_DATA_DIR_NAME = "ProjectCortana"
VERSION = "0.1.0"

# Session capabilities
HISTORY_PERSISTENCE_ENABLED = False
EXPLICIT_PERSISTENT_MEMORY_ENABLED = True
ACTIVE_MEMORY_PERSISTENCE_ENABLED = False
KNOWLEDGE_VAULT_ENABLED = True
# Document text reaches the AI only through explicit /ask-docs.
DOCUMENT_CONTEXT_INJECTION_ENABLED = True
LOCAL_DOCUMENT_RETRIEVAL_ENABLED = True
SEMANTIC_RETRIEVAL_ENABLED = False
SOURCE_MANIFEST_PERSISTENCE_ENABLED = False

# Explicit persistent memory limits and storage
MAX_MEMORY_TEXT_LENGTH = 2000
MEMORY_FILENAME = "memories.json"

# Active memory context limits (session-only AI reference context)
MAX_ACTIVE_MEMORIES = 10
MAX_ACTIVE_MEMORY_CHARS = 8000

# Knowledge Vault limits and storage
MAX_DOCUMENT_SOURCE_BYTES = 10 * 1024 * 1024
MAX_DOCUMENT_TEXT_LENGTH = 500_000
MAX_STORED_DOCUMENTS = 100
ALLOWED_DOCUMENT_EXTENSIONS = frozenset({".txt", ".md", ".pdf"})
DOCUMENT_VAULT_FILENAME = "documents.json"

# Deterministic local document chunking and retrieval
TARGET_CHUNK_SIZE = 1200
CHUNK_OVERLAP = 150
MIN_CHUNK_LENGTH = 40
MAX_CHUNKS_PER_DOCUMENT = 500
MAX_RETRIEVED_CHUNKS = 8
MAX_RETRIEVED_CONTEXT_CHARS = 12_000
MAX_SEARCH_RESULT_PREVIEW_CHARS = 200
MAX_SEARCH_DOCS_RESULTS = 5

# Security incident repository and evidence foundation (Milestone 8)
INCIDENT_REPOSITORY_ENABLED = True
EVIDENCE_COPY_ENABLED = True
CHAIN_OF_CUSTODY_ENABLED = True
AUTOMATED_RESPONSE_ENABLED = False
EXTERNAL_THREAT_INTELLIGENCE_LOOKUPS_ENABLED = False
INCIDENT_AI_CONTEXT_INJECTION_ENABLED = False
INCIDENT_REPOSITORY_PERSISTENCE_ENABLED = True
INCIDENT_SINGLE_INSTANCE_COORDINATION_ENABLED = False

INCIDENT_REPOSITORY_SCHEMA_VERSION = 1
INCIDENT_REPOSITORY_FILENAME = "incidents.json"
EVIDENCE_STORE_DIRNAME = "evidence"

MAX_EVENT_TITLE_LENGTH = 200
MAX_EVENT_DESCRIPTION_LENGTH = 5_000
MAX_EVENT_SOURCE_LENGTH = 200
MAX_INCIDENT_TITLE_LENGTH = 200
MAX_INCIDENT_SUMMARY_LENGTH = 5_000
MAX_INDICATOR_VALUE_LENGTH = 2_000
MAX_INDICATOR_NOTES_LENGTH = 2_000
MAX_EVIDENCE_TITLE_LENGTH = 200
MAX_EVIDENCE_DESCRIPTION_LENGTH = 5_000
MAX_EVIDENCE_FILENAME_LENGTH = 255
MAX_EVIDENCE_SOURCE_BYTES = 50 * 1024 * 1024
MAX_NOTE_TEXT_LENGTH = 5_000
MAX_CUSTODY_ACTOR_LENGTH = 200
MAX_CUSTODY_REASON_LENGTH = 1_000
MAX_CUSTODY_NOTES_LENGTH = 2_000
MAX_TAG_LENGTH = 64
MAX_TAGS_PER_RECORD = 20
MAX_SECURITY_LIST_PREVIEW_CHARS = 120
INDICATOR_CONFIDENCE_MIN = 0
INDICATOR_CONFIDENCE_MAX = 100

# Defensive tool framework (Milestone 9)
DEFENSIVE_TOOL_FRAMEWORK_ENABLED = True
TOOL_SCOPE_ENFORCEMENT_ENABLED = True
TOOL_HUMAN_APPROVAL_ENABLED = True
TOOL_DRY_RUN_ENFORCEMENT_ENABLED = True
ARBITRARY_SHELL_EXECUTION_ENABLED = False
EXTERNAL_TOOL_EXECUTION_ENABLED = False
AUTONOMOUS_REMEDIATION_ENABLED = False
TOOL_AUDIT_PERSISTENCE_ENABLED = True
TOOL_SINGLE_INSTANCE_COORDINATION_ENABLED = False
TOOL_AI_CONTEXT_INJECTION_ENABLED = False

TOOL_CONTROL_REPOSITORY_SCHEMA_VERSION = 1
TOOL_CONTROL_REPOSITORY_FILENAME = "tool_control.json"

MAX_TOOL_NAME_LENGTH = 100
MAX_TOOL_DESCRIPTION_LENGTH = 1_000
MAX_TOOL_JUSTIFICATION_LENGTH = 2_000
MAX_TOOL_SCOPE_NAME_LENGTH = 200
MAX_TOOL_SCOPE_NOTES_LENGTH = 2_000
MAX_TOOL_APPROVAL_REASON_LENGTH = 1_000
MAX_TOOL_RESULT_SUMMARY_LENGTH = 2_000
MAX_TOOL_AUDIT_DETAILS_LENGTH = 1_000
MAX_TOOL_PARAMETER_STRING_LENGTH = 2_000
MAX_TOOL_FILE_BYTES = 10 * 1024 * 1024
MAX_TOOL_OUTPUT_CHARS = 8_000
MAX_TOOL_TEXT_SEARCH_MATCHES = 50
MAX_TOOL_TEXT_SEARCH_PREVIEW_CHARS = 120
MAX_TOOL_TIMEOUT_SECONDS = 30
DEFAULT_TOOL_TIMEOUT_SECONDS = 10
MAX_TOOL_LIST_PREVIEW_CHARS = 120
FINGERPRINT_DISPLAY_PREFIX_CHARS = 12

# Defensive workflow orchestration (Milestone 10)
DEFENSIVE_WORKFLOW_ORCHESTRATION_ENABLED = True
WORKFLOW_AI_CONTEXT_INJECTION_ENABLED = False
WORKFLOW_EXTERNAL_PLAYBOOK_LOADING_ENABLED = False
WORKFLOW_DYNAMIC_STEP_BINDING_ENABLED = False
WORKFLOW_PARALLEL_EXECUTION_ENABLED = False
WORKFLOW_BACKGROUND_EXECUTION_ENABLED = False
WORKFLOW_NESTED_PLAYBOOKS_ENABLED = False

# Persistent workflow operations and incident linkage (Milestone 11)
WORKFLOW_RUN_PERSISTENCE_ENABLED = True
WORKFLOW_INCIDENT_LINKAGE_ENABLED = True
WORKFLOW_SINGLE_INSTANCE_COORDINATION_ENABLED = False
WORKFLOW_REPOSITORY_SCHEMA_VERSION = 1
WORKFLOW_REPOSITORY_FILENAME = "workflow_runs.json"

MAX_WORKFLOW_STEPS = 8
MAX_WORKFLOW_RUNTIME_SECONDS = 60
MAX_WORKFLOW_NAME_LENGTH = 100
MAX_WORKFLOW_DESCRIPTION_LENGTH = 1_000
MAX_WORKFLOW_VERSION_LENGTH = 32
MAX_WORKFLOW_STEP_ID_LENGTH = 100
MAX_WORKFLOW_STEP_DESCRIPTION_LENGTH = 500
MAX_WORKFLOW_ERROR_MESSAGE_LENGTH = 500
MAX_WORKFLOW_RUNS_RETAINED = 100
MAX_WORKFLOW_AUDIT_ENTRIES_RETAINED = 500
MAX_WORKFLOW_LIST_PREVIEW_CHARS = 120
MAX_WORKFLOW_AUDIT_DETAILS_LENGTH = 1_000


def _default_app_data_dir() -> Path:
    """Return the user-local application data directory for Project Cortana."""
    if os.name == "nt":
        local_app_data = os.environ.get("LOCALAPPDATA", "").strip()
        if local_app_data:
            return Path(local_app_data) / APP_DATA_DIR_NAME
        return Path.home() / "AppData" / "Local" / APP_DATA_DIR_NAME

    xdg_data_home = os.environ.get("XDG_DATA_HOME", "").strip()
    if xdg_data_home:
        return Path(xdg_data_home) / APP_DATA_DIR_NAME

    return Path.home() / ".local" / "share" / APP_DATA_DIR_NAME


def get_default_memory_file_path() -> Path:
    """Return the default user-local path for explicit persistent memories."""
    return _default_app_data_dir() / MEMORY_FILENAME


def get_default_document_vault_file_path() -> Path:
    """Return the default user-local path for Knowledge Vault documents."""
    return _default_app_data_dir() / DOCUMENT_VAULT_FILENAME


def get_default_incident_repository_file_path() -> Path:
    """Return the default user-local path for the incident repository JSON file."""
    return _default_app_data_dir() / INCIDENT_REPOSITORY_FILENAME


def get_default_evidence_store_dir_path() -> Path:
    """Return the default user-local directory for copied evidence files."""
    return _default_app_data_dir() / EVIDENCE_STORE_DIRNAME


def get_default_tool_control_repository_file_path() -> Path:
    """Return the default user-local path for the tool-control repository JSON file."""
    return _default_app_data_dir() / TOOL_CONTROL_REPOSITORY_FILENAME


def get_default_workflow_repository_file_path() -> Path:
    """Return the default user-local path for the workflow repository JSON file."""
    return _default_app_data_dir() / WORKFLOW_REPOSITORY_FILENAME
